application: {YOUR_APPLICATION}
version: {YOUR_APPLICATION_VERSION}
runtime: go
api_version: go1
threadsafe: no

handlers:
- url: /$
  static_files: pub/index.html
  upload: pub/index.html$
- url: /css
  static_dir: pub/css
- url: /js
  static_dir: pub/js
- url: /img
  static_dir: pub/img
- url: /ipa
  static_dir: pub/ipa
  mime_type: "application/octet-stream"
- url: /plist
  static_dir: pub/plist
  mime_type: "application/x-plist"
- url: /apps/$
  static_files: pub/apps/index.html
  upload: pub/apps/index.html$
  secure: always
- url: /(apps/.*\.html)$
  static_files: pub/\1
  upload: pub/(apps/.*\.html)$
  secure: always
- url: /(apps/.*)/$
  static_files: pub/\1/index.html
  upload: pub/(apps/.*/index.html)$
  secure: always
- url: /apps/.*
  script: _go_app
  secure: always
- url: /api/.*
  script: _go_app
  secure: always

env_variables:
  config_default_html: index.html
  config_auth_dir: /apps/
  config_auth_realm: {YOUR_BASIC_AUTH_REALM}
  config_auth_user: {YOUR_BASIC_AUTH_USER_NAME}
  config_auth_pass: {YOUR_BASIC_AUTH_PASSWORD}
  config_auth_bucket: {YOUR_BASIC_AUTH_GCS_BUCKET_NAME}
  config_auth_object_root: {YOUR_BASIC_AUTH_OBJECT_ROOT}
  config_pub_dir: /
  config_pub_bucket: {YOUR_PUB_BUCKET_NAME}
  config_pub_object_root: {YOUR_PUB_OBJECT_ROOT}